apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      role: {{ .Values.labels.role }}
      tier: {{ .Values.labels.tier }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        role: {{ .Values.labels.role }}
        tier: {{ .Values.labels.tier }}
    spec:
      containers:
      - name: {{ .Values.labels.app }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
