apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytomorrow-web
  labels:
    app: mytomorrow-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mytomorrow-web
  template:
    metadata:
      labels:
        app: mytomorrow-web
    spec:
      containers:
        - name: mytomorrows-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
